services:
  rag_pstgrs:
    # image: postgres:latest
    image: pgvector/pgvector:pg17
    container_name: rag_pstgrs
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: games
    ports:
      - "5432:5432"
    volumes:
      - ./storage:/var/lib/postgresql/data
      - ./init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8100:8080

  rag_app:
    # platform: linux/amd64
    platform: linux/x86_64
    build: .
      #context: .
    # restart: unless-stopped
    image: rag
    container_name: rag_app
    depends_on:
      - rag_pstgrs
    environment:
      DATABASE_URL: postgres://root:root@rag_pstgrs:5432/games
    volumes:
      - .:/application
    ports:
      - "8000:8000"

# volumes:
#   storage_named_volume:
